#!/bin/bash
while :
do
  if pidof node > /dev/null
  then
    #curl http://textbelt.com/text -d number=7747661063 -d "message=Server is on"
    sleep 30s
  else
    sudo shiny-server > ServerLog
    curl http://textbelt.com/text -d number=7747661063 -d "message=Server restart"
    sleep 30s
  fi
done
